/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.mycompany.crudproductos;

/**
 *
 * @author PC-05
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class FrmProductos extends javax.swing.JInternalFrame {

    /** Creates new form FrmProductos */
    public FrmProductos() {
        initComponents();
        setLocationRelativeTo(null);
        txtId.setEnabled(false);
        tblProductos.setSelectionMode(
            ListSelectionModel.SINGLE_SELECTION
        );
        cargarCategorias();
        listarProductos();
        estadoInicial();        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lblproducto = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lblstock = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategoria.addActionListener(this::cboCategoriaActionPerformed);

        btnNuevo.setText("NUEVO");

        btnGuardar.setText("GUARDAR");

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("ELIMINAR");

        btnCancelar.setText("CANCELAR");

        lblid.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblid.setText("ID : ");

        lblproducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblproducto.setText("Producto : ");

        lblcategoria.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblcategoria.setText("Categoría :");

        lblprecio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblprecio.setText("Precio :");

        lblstock.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblstock.setText("Stock :");

        jTextField5.setBackground(new java.awt.Color(0, 51, 153));
        jTextField5.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("GESTIÓN DE PRODUCTOS                          SENATI");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Categoría", "Precio", "Stock"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblproducto)
                            .addComponent(lblid)
                            .addComponent(lblcategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEliminar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblprecio)
                                            .addComponent(lblstock))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(txtStock)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancelar)
                                        .addGap(50, 50, 50))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnNuevo)
                        .addGap(37, 37, 37)
                        .addComponent(btnGuardar)
                        .addGap(32, 32, 32)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblid)
                        .addGap(29, 29, 29)
                        .addComponent(lblproducto)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcategoria)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblprecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblstock)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnCancelar))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        
        // Seleccionar un registro del JTable
        int fila = tblProductos.getSelectedRow();
        if (fila >= 0) {
            txtId.setText(
                tblProductos.getValueAt(fila, 0).toString()
            );
            txtNombre.setText(
                tblProductos.getValueAt(fila, 1).toString()
            );
            cboCategoria.setSelectedItem(
                tblProductos.getValueAt(fila, 2).toString()
            );
            txtPrecio.setText(
                tblProductos.getValueAt(fila, 3).toString()
            );
            txtStock.setText(
                tblProductos.getValueAt(fila, 4).toString()
            );
            estadoEdicion();
        }     
        
    }//GEN-LAST:event_tblProductosMouseClicked
    // TODO add your handling code here:
    // TODO add your handling code here:
    // TODO add your handling code here:
    // TODO add your handling code here:
    // TODO add your handling code here:

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblproducto;
    private javax.swing.JLabel lblstock;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    
    // Método para activar o bloquear campos
    private void habilitarCampos(boolean estado) {
        txtNombre.setEnabled(estado);
        cboCategoria.setEnabled(estado);
        txtPrecio.setEnabled(estado);
        txtStock.setEnabled(estado);
    }
    
    // Estado inicial
    private void estadoInicial() {
        habilitarCampos(false);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    // Estado Nuevo
    private void estadoNuevo() {
        habilitarCampos(true);
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(true);
    }
    
    // Estado Edición
    private void estadoEdicion() {
        habilitarCampos(true);
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }
    
    // Mapa de categorias
    private Map<String, Integer> categorias =
        new HashMap<>();
    
    // Cargar categorías desde MySQL
    private void cargarCategorias() {
        cboCategoria.removeAllItems();
        categorias.clear();
        String sql =
            "SELECT id_categoria, nombre " +
            "FROM categoria " +
            "ORDER BY nombre";
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                int id = rs.getInt("id_categoria");
                String nombre = rs.getString("nombre");
                cboCategoria.addItem(nombre);
                categorias.put(nombre, id);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al cargar categorías: " + e.getMessage()
            );
        }
    }
    
    // READ: listar productos en JTable
    private void listarProductos() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{
                "ID", "Producto", "Categoría", "Precio", "Stock"
            }, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String sql =
            "SELECT p.id_producto, p.nombre, " +
            "c.nombre AS categoria, p.precio, p.stock " +
            "FROM producto p " +
            "INNER JOIN categoria c " +
            "ON p.id_categoria = c.id_categoria " +
            "ORDER BY p.id_producto";
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getString("nombre"),
                    rs.getString("categoria"),
                    rs.getDouble("precio"),
                    rs.getInt("stock")
                };
                modelo.addRow(fila);
            }
            tblProductos.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al listar productos: " + e.getMessage()
            );
        }
    }    
    
    // Validar campos obligatorios
    private boolean validarCampos() {
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Ingrese el nombre del producto");
            txtNombre.requestFocus();
            return false;
        }
        if (cboCategoria.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una categoría");
            return false;
        }
        if (txtPrecio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Ingrese el precio");
            txtPrecio.requestFocus();
            return false;
        }
        if (txtStock.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Ingrese el stock");
            txtStock.requestFocus();
            return false;
        }
        return true;
    }      
    
    // Obtener un precio válido
    private Double obtenerPrecioValido() {
       try {
           double precio = Double.parseDouble(
               txtPrecio.getText().trim()
           );
           if (precio <= 0) {
               JOptionPane.showMessageDialog(this,
                   "El precio debe ser mayor que cero");
               txtPrecio.requestFocus();
               return null;
           }
           return precio;
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this,
               "Ingrese un precio válido");
           txtPrecio.requestFocus();
           return null;
       }
    }    
    
    // Obtener un stock válido
    private Integer obtenerStockValido() {
        try {
            int stock = Integer.parseInt(
                txtStock.getText().trim()
            );
            if (stock < 0) {
                JOptionPane.showMessageDialog(this,
                    "El stock no puede ser negativo");
                txtStock.requestFocus();
                return null;
            }
            return stock;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Ingrese un stock válido");
            txtStock.requestFocus();
            return null;
        }
    }    

    // Limpiar el formulario
    private void limpiar() {
        txtId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        if (cboCategoria.getItemCount() > 0) {
            cboCategoria.setSelectedIndex(0);
        }
        tblProductos.clearSelection();
    }
    
    // Botón NUEVO
    private void btnNuevoActionPerformed(
            java.awt.event.ActionEvent evt) {
        limpiar();
        estadoNuevo();
        txtNombre.requestFocus();
    }
    
    // 11.3 Botón CANCELAR
    private void btnCancelarActionPerformed(
            java.awt.event.ActionEvent evt) {
        limpiar();
        estadoInicial();
    }
    
    // CREATE: guardar un producto
    private void guardarProducto() {
        if (!validarCampos()) {
            return;
        }
        Double precio = obtenerPrecioValido();
        if (precio == null) {
            return;
        }
        Integer stock = obtenerStockValido();
        if (stock == null) {
            return;
        }
        String nombre = txtNombre.getText().trim();
        String categoria = cboCategoria.getSelectedItem().toString();
        int idCategoria = categorias.get(categoria);
        String sql =
            "INSERT INTO producto " +
            "(nombre, id_categoria, precio, stock) " +
            "VALUES (?, ?, ?, ?)";
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, nombre);
            ps.setInt(2, idCategoria);
            ps.setDouble(3, precio);
            ps.setInt(4, stock);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Producto registrado correctamente");
            listarProductos();
            limpiar();
            estadoInicial();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al registrar: " + e.getMessage());
        }
    }    
    
    // Evento del botón GUARDAR
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardarProducto();
    }    

    //UPDATE: modificar un producto
    private void actualizarProducto() {
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Seleccione un producto");
            return;
        }
        if (!validarCampos()) {
            return;
        }
        Double precio = obtenerPrecioValido();
        if (precio == null) {
            return;
        }
        Integer stock = obtenerStockValido();
        if (stock == null) {
            return;
        }
        int idProducto = Integer.parseInt(txtId.getText());
        String nombre = txtNombre.getText().trim();
        String categoria = cboCategoria.getSelectedItem().toString();
        int idCategoria = categorias.get(categoria);
        String sql =
            "UPDATE producto SET " +
            "nombre = ?, id_categoria = ?, " +
            "precio = ?, stock = ? " +
            "WHERE id_producto = ?";
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, nombre);
            ps.setInt(2, idCategoria);
            ps.setDouble(3, precio);
            ps.setInt(4, stock);
            ps.setInt(5, idProducto);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Producto actualizado correctamente");
            listarProductos();
            limpiar();
            estadoInicial();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar: " + e.getMessage());
        }
    }
    
    // Evento del botón ACTUALIZAR
    private void btnActualizarActionPerformed(
            java.awt.event.ActionEvent evt) {
        actualizarProducto();
    } 
    
    // DELETE: eliminar un producto
    // Eliminar es una operación irreversible. Por eso, antes del DELETE se solicita confirmación al usuario.
    private void eliminarProducto() {
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Seleccione un producto");
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar " +
                txtNombre.getText() + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }
        String sql =
            "DELETE FROM producto " +
            "WHERE id_producto = ?";
        try (Connection cn = Conexion.conectar();
             PreparedStatement ps = cn.prepareStatement(sql)) {
            int id = Integer.parseInt(txtId.getText());
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,
                "Producto eliminado correctamente");
            listarProductos();
            limpiar();
            estadoInicial();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al eliminar: " + e.getMessage());
        }
    }    
    
    // Evento del botón ELIMINAR
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        eliminarProducto();
    }    

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
    
}
